name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
env:
  USERNAME: github-actions[bot]
  USEREMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  USERTOKEN: ${{ secrets.PLATFORM_BOT_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '17.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@sequencehq'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}